### ISSUE TITLE
mapped dictionary has element type `Any`

### ISSUE THREAD

**Issue by gaurav-arya** [andyferris/Dictionaries.jl#99] opened 2022-04-24 20:38 UTC
In the following code, the mapped dictionary has element type `Any`.

```
julia> using Dictionaries
julia> x = 3
3
julia> d = Dictionary([4], [5])
1-element Dictionary{Int64, Int64}
 4 │ 5
julia> map(val -> val + x, d)
1-element Dictionary{Int64, Any}
 4 │ 8
```
This seems to be because `Core.Compiler.return_type` returns `Any`, due to the global `x`:
```
julia> Core.Compiler.return_type(val->val+x, (Int64,))
Any
```

However, I would expect the element type to still be `Int64` based on the fact that elements of the outputted dictionary have type `Int64`, which would match the behaviour of `Base.map`:
```
julia> map(val -> val + x, [4])
1-element Vector{Int64}:
 7
```

**Comment by gaurav-arya** [comment] 2022-04-24 20:49
Just saw https://github.com/andyferris/Dictionaries.jl/issues/28; this might be related / a duplicate

**Comment by andyferris** [comment] 2022-05-04 21:57
Yes, currently we are using `return_type`, and we might one day resolve #28.

In practice people shouldn't be using globals that way in performance-critical code, and for playing at the REPL it shouldn't have a big effect.

**Comment by andyferris** [comment] 2022-05-04 21:58
Maybe I'll just close this as a duplicate of #28?

**Closed by andyferris** 2022-05-04 21:58 UTC
